lib/bpf: add missing limits.h to bpf_glue.c
Function get_libbpf_version() relies on PATH_MAX, which is defined by POSIX
and included in <limits.h>.

This fixes an error seen using GCC 10.2.0 and Binutils 2.35.1 when cross-
compiling for OpenWrt:

bpf_glue.c: In function 'get_libbpf_version':
bpf_glue.c:46:11: error: 'PATH_MAX' undeclared (first use in this function);
did you mean 'AF_MAX'?
   46 |  char buf[PATH_MAX], *s;
      |           ^~~~~~~~
      |           AF_MAX
bpf_glue.c:46:11: note: each undeclared identifier is reported only once for
each function it appears in
bpf_glue.c:46:7: warning: unused variable 'buf' [-Wunused-variable]
   46 |  char buf[PATH_MAX], *s;
      |       ^~~
make[5]: *** [../config.mk:43: bpf_glue.o] Error 1

Signed-off-by: Tony Ambardar <Tony.Ambardar@gmail.com>